### PR TITLE
[VAN-20253] Update Codes API documentation - add description

### PR DESCRIPTION
**Pull request by brunck**
@shaisachs @NGPVAN/olive 

To reflect adding the description property to the CodeDto in the VAN API.

### CODE REVIEW

**Comment by shaisachs** [comment]
Since /codes accepts POST and PUT, can you clarify whether description is Read-only, or available for writing?  If it's available for writing - can you update the sample requests in those sections?

Otherwise, looks good!

**Comment by brunck** [comment]
@shaisachs Updated. Please take a look.

**Comment by shaisachs** [comment]
Rockin, thanks!  Go ahead and merge as you like.

**Comment by brunck** [comment]
@shaisachs Hey Shai the related code to this documentation change I believe has worked its way to develop.

**Comment by brunck** [comment]
@shaisachs Hey I think the code was released today, 7/20/16.

**Comment by shaisachs** [comment]
Awesome, thanks!  Have a few other irons in the fire but I'll make sure to get that out the door soon.

**Comment by shaisachs** [comment]
This item is live now.  I'll add a note about it to the changelog as well.

**Pull request merged**
