### PR TITLE
NGP API improvements

### PR DESCRIPTION
**Pull request by shaisachs**
* Email lists
* Add emailLists to GET / POST contacts endpoints
* GET /contacts/$contactId

cc @mikeholczer @AimanZidan

### CODE REVIEW

**Comment by shaisachs** [comment]
I intentionally left /donorSummaries out of the docs, because I don't think we really want to provide this data publicly.  At least, I don't want to provide it this way (seems like contacts/$contactId/contributions would be better perhaps.)  But I'm open to other thoughts.

**Comment by AimanZidan** [comment]
why not? we have a similliar api in v1

**Comment by shaisachs** [comment]
I guess it just feels not very RESTful to me.  And also, I don't know how much we actually want to encourage clients to use this functionality.

**Comment by rwinikates** [comment]
@shaisachs are we just waiting on @mikeholczer to sign off for this to be merged?

**Comment by mikeholczer** [comment]
It would be @lnmorton sign-off that would be needed, but it doesn't look like the concerns about the contribution methods got resolved.

**Comment by lnmorton** [comment]
Can someone give me a precis of what I'm signing off on here?

**Comment by shaisachs** [comment]
No this one should be straight up closed I think.  IIRC we decided not to proceed with it.

**Pull request closed without merging**
