### PR TITLE
Fix code blocks overflowing

### PR DESCRIPTION
**Pull request by rwinikates**
as seen: https://gyazo.com/8dd97217e1e6606b8a2f75939d5d4cd3
it becomes: https://gyazo.com/9534ce640f0671c6a51c6df0f716e917

### CODE REVIEW

**Comment by BaconSoap** [comment]
Can we get rid of the vertical scroll bars, or is that a browser-specific thing?

**Comment by shaisachs** [comment]
Cool, I say merge it!

**Comment by rwinikates** [comment]
@BaconSoap good suggestion, updated. Good to merge?

**Comment by BaconSoap** [comment]
:shipit: :exclamation::grey_exclamation::exclamation:

**Pull request merged**
