### PR TITLE
Merge develop into master

### PR DESCRIPTION
**Pull request by DMcCann**
Creating a PR per [this request](https://github.com/NGPVAN/developers.ngpvan.com/pull/104#issuecomment-211942364). @mattglet and any other interested parties - please review

### CODE REVIEW

**Comment by mattglet** [comment]
@BaconSoap @peter-tomaselli You guys have commits here - is your corresponding work live already?  More specifically, is there a reason your documentation should not go live?

**Comment by BaconSoap** [comment]
:+1: do it live!

**Comment by peter-tomaselli** [comment]
No problems from me :+1:

**Comment by mattglet** [comment]
@itsdrewmiller what's the process of pushing these docs live? We'll want to do it on Friday after the DNC release.

**Comment by itsdrewmiller** [comment]
@rwinikates

**Comment by mattglet** [comment]
@DMcCann go ahead and merge.  Thanks!

**Pull request merged**
